name: Main workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - run: git config --global url."https://".insteadOf git://
      - run: flutter --version
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: powershell -Command "(gc D:\a\hk_launcher\hk_launcher\windows\flutter\ephemeral\.plugin_symlinks\system_theme\windows\system_theme_plugin.cpp) -replace 'GetDarkModeEnabled', 'GetAppDarkModeEnabled' | Out-File D:\a\hk_launcher\hk_launcher\windows\flutter\ephemeral\.plugin_symlinks\system_theme\windows\system_theme_plugin.cpp"
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
         name: hk_launcher
         path: build/windows/runner/Release
